### PR TITLE
Added processing containers.

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

**Comment by justinlittman** [comment]
Goofed and added API credentials changes to this PR.  But life will go on.

**Comment by kerchner** [comment]
@justinlittman Doing a double check on the smoke tests before merging yielded:
```
kerchner@gwdev-kerchner-14:~/projects/sfm-docker (sfm_227-iteration_env)$ docker-compose -f master.docker-compose.yml up -d
Pulling sfmrabbit (rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3)...
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```
Changing the Rabbitmq tag to 3-management did not resolve this.  I don't see any container names in master.docker-compose.yml that use characters that don't match that regex.  Isolating just the first container definition (sfmrabbit) indicates that the problem lies with this one (sfmrabbit).

**Comment by justinlittman** [comment]
@kerchner - I couldn't replicate the problem.  I removed the rabbit image and re-pulled it just fine.  I wonder if it was a transient problem with docker hub or you need to upgrade docker/docker-compose.

```
GLSS-F0G5RP:sfm-docker justinlittman$ docker --version
Docker version 1.10.3, build 20f81dd
GLSS-F0G5RP:sfm-docker justinlittman$ docker-compose --version
docker-compose version 1.6.2, build 4d72027
```

**Comment by kerchner** [comment]
@justinlittman Upgrading docker-compose (was 1.4, now 1.7.1) seemed to resolve the problem - and/or perhaps it was a transient docker-hub issue.  Thanks for the suggestion.

**Pull request merged**
